import type { PageConfig, PageConfiguration } from './pageTypes.js';

// ─────────────────────────────────────────────────────────────────────────────
// AUTO-GENERATED by excelToJson.ts
// Generated: 2026-03-09T02:59:05.519Z
//
// DO NOT EDIT BY HAND
// ─────────────────────────────────────────────────────────────────────────────

export const booksConfig: Record<string, PageConfig> = {

  'nfl': {
    pages: [
    {
      type: 'list',
      title: "NFL MVP Challenge",
      description: "List the NFL Most Valuable Players (2000-2024).",
      category: "Awards",
      difficulty: 'Hard',
      items: Array.from({length: 25}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/awards/ap-nfl-mvp-award.htm",
      actionContent: {
        content: "One Year has Co-MVPs bonus points if you get the year and both players right!",
        position: 'right',
        rotation: 3,
        icon: '🧠'
      }
    },

    {
      type: 'list',
      title: "NFL Defensive Player of the Year",
      description: "List the NFL Defensive Players of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/awards/ap-defensive-player-of-the-year.htm",
    },

    {
      type: 'list',
      title: "NFL Offensive Rookie of the Year",
      description: "List the NFL Offensive Rookies of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/awards/ap-offensive-rookie-of-the-year-award.htm",
    },

    {
      type: 'list',
      title: "NFL Defensive Rookie of the Year",
      description: "List the NFL Defensive Rookies of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/awards/ap-defensive-rookie-of-the-year-award.htm",
    },

    {
      type: 'list',
      title: "NFL Comeback Player of the Year",
      description: "List the NFL Comeback Players of the Year (2015-2024).",
      category: "Awards",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: 2024 - i,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/awards/ap-comeback-player-award.htm",
    },

    {
      type: 'matchup',
      title: "Last 10 AFC Championship Games",
      description: "Fill in the teams that played in each AFC Championship game.",
      category: "Matchups",
      difficulty: 'Medium',
      items: [
        { centerText: "vs", context: "2024" },
        { centerText: "vs", context: "2023" },
        { centerText: "vs", context: "2022" },
        { centerText: "vs", context: "2021" },
        { centerText: "vs", context: "2020" },
        { centerText: "vs", context: "2019" },
        { centerText: "vs", context: "2018" },
        { centerText: "vs", context: "2017" },
        { centerText: "vs", context: "2016" },
        { centerText: "vs", context: "2015" },
      ],
      columns: 2,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/last-10-afc-championship-games",
    },

    {
      type: 'matchup',
      title: "Last 10 NFC Championship Games",
      description: "Fill in the teams that played in each NFC Championship game.",
      category: "Matchups",
      difficulty: 'Medium',
      items: [
        { centerText: "vs", context: "2024" },
        { centerText: "vs", context: "2023" },
        { centerText: "vs", context: "2022" },
        { centerText: "vs", context: "2021" },
        { centerText: "vs", context: "2020" },
        { centerText: "vs", context: "2019" },
        { centerText: "vs", context: "2018" },
        { centerText: "vs", context: "2017" },
        { centerText: "vs", context: "2016" },
        { centerText: "vs", context: "2015" },
      ],
      columns: 2,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/last-10-nfc-championship-games",
    },

    {
      type: 'matchup',
      title: "Super Bowl Matchups by Score",
      description: "Name the teams that played in these Super Bowls based on the final score.",
      category: "Matchups",
      difficulty: 'Hard',
      items: [
        { centerText: "31-17", context: "Super Bowl LVIII (2024)" },
        { centerText: "38-35", context: "Super Bowl LVII (2023)" },
        { centerText: "23-20", context: "Super Bowl LVI (2022)" },
        { centerText: "31-9", context: "Super Bowl LV (2021)" },
        { centerText: "31-20", context: "Super Bowl LIV (2020)" },
        { centerText: "13-3", context: "Super Bowl LIII (2019)" },
      ],
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/super-bowl/",
      actionContent: {
        content: "Some of these were nail-biters, others were blowouts!",
        position: 'right',
        rotation: -2,
        icon: '🏆'
      }
    },

    {
      type: 'list',
      title: "NFL All-Time Touchdown Leaders",
      description: "List the top 20 all-time NFL touchdown leaders.",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.espn.com/nfl/history/leaders",
      actionContent: {
        content: "Only one active player is on this list!",
        position: 'left',
        rotation: 2,
        icon: '🏃‍♂️'
      }
    },

    {
      type: 'list',
      title: "Top 20 NFL Career Rushing Leaders",
      description: "List the top 20 all-time NFL career rushing leaders.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/leaders/rush_yds_career.htm",
      actionContent: {
        content: "There is one active player in this list",
        position: 'right',
        rotation: -1,
        icon: '🏃‍♂️'
      }
    },

    {
      type: 'list',
      title: "Top 20 Single Season NFL Rushing Records",
      description: "List the top 20 single season NFL rushing records.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/leaders/rush_yds_single_season.htm",
      actionContent: {
        content: "2 RBs show up twice and there is a tie at #12",
        position: 'left',
        rotation: -3,
        icon: '🏃‍♂️'
      }
    },

    {
      type: 'list',
      title: "Top 20 NFL Career Receiving Yards Leaders",
      description: "List the top 20 all-time NFL career receiving yards leaders.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/leaders/rec_yds_career.htm",
      actionContent: {
        content: "Only one active player",
        position: 'right',
        rotation: 2,
        icon: '🏈'
      }
    },

    {
      type: 'list',
      title: "Top 20 Single Season NFL Receiving Yards Records",
      description: "List the top 20 single season NFL receiving yards records.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 20}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/leaders/rec_yds_single_season.htm",
    },

    {
      type: 'list',
      title: "2024 Fantasy Football Top 10 (PPR)",
      description: "List the top 10 overall fantasy scorers in full PPR during the 2024 regular season.",
      category: "Other",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/years/2024/fantasy.htm#fantasy::27",
      actionContent: {
        content: "Half are non-QB",
        position: 'right',
        rotation: 3,
        icon: '🏈'
      }
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC East teams (yards accumulated while on NFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-nfc-east-by-player",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC East teams (yards accumulated while on NFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-nfc-east-by-player",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC East teams (yards accumulated while on NFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-nfc-east-by-player",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC North teams (yards accumulated while on NFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-nfc-north-by-player",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC North teams (yards accumulated while on NFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-nfc-north-by-player",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC North teams (yards accumulated while on NFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-nfc-north-by-player",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC South teams (yards accumulated while on NFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-nfc-south-by-player",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC South teams (yards accumulated while on NFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-nfc-south-by-player",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC South teams (yards accumulated while on NFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-nfc-south-by-player",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for NFC West teams (yards accumulated while on NFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-nfc-west-by-player",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for NFC West teams (yards accumulated while on NFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-nfc-west-by-player",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for NFC West teams (yards accumulated while on NFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-nfc-west-by-player",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC East teams (yards accumulated while on AFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-afc-east-by-player",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC East teams (yards accumulated while on AFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-afc-east-by-player",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC East teams (yards accumulated while on AFC East teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-afc-east-by-player",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC North teams (yards accumulated while on AFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-afc-north-by-player",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC North teams (yards accumulated while on AFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-afc-north-by-player",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC North teams (yards accumulated while on AFC North teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-afc-north-by-player",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC South teams (yards accumulated while on AFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-afc-south-by-player",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC South teams (yards accumulated while on AFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-afc-south-by-player",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC South teams (yards accumulated while on AFC South teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-afc-south-by-player",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Career Passing Yards (By Player)",
      description: "List the top 10 career passing yard leaders for AFC West teams (yards accumulated while on AFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-afc-west-by-player",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Career Rushing Yards (By Player)",
      description: "List the top 10 career rushing yard leaders for AFC West teams (yards accumulated while on AFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-afc-west-by-player",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Career Receiving Yards (By Player)",
      description: "List the top 10 career receiving yard leaders for AFC West teams (yards accumulated while on AFC West teams).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-afc-west-by-player",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-nfc-east-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-nfc-east-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC East — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-nfc-east-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-nfc-north-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-nfc-north-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC North — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-nfc-north-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-nfc-south-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-nfc-south-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC South — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-nfc-south-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among NFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-nfc-west-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among NFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-nfc-west-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "NFC West — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among NFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-nfc-west-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-afc-east-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-afc-east-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC East — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC East teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-afc-east-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-afc-north-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-afc-north-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC North — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC North teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-afc-north-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-afc-south-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-afc-south-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC South — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC South teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-afc-south-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Passing Yards (Last 10 Seasons)",
      description: "List the top 10 passing yard leaders from the most recent 10 NFL seasons among AFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-yards-by-afc-west-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Rushing Yards (Last 10 Seasons)",
      description: "List the top 10 rushing yard leaders from the most recent 10 NFL seasons among AFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-afc-west-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "AFC West — Top 10 Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 receiving yard leaders from the most recent 10 NFL seasons among AFC West teams.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-yards-by-afc-west-players-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "Top 10 Career Sacks (All-Time)",
      description: "List the top 10 NFL players by career sacks (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-sacks-in-nfl-history-by-a-player",
    },

    {
      type: 'list',
      title: "Top 10 Career Interceptions (All-Time)",
      description: "List the top 10 NFL players by career interceptions (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-interceptions-by-player-nfl-history",
    },

    {
      type: 'list',
      title: "Top 10 Career Forced Fumbles (All-Time)",
      description: "List the top 10 NFL players by career forced fumbles (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-forced-fumbles-in-nfl-history-by-a-player",
    },

    {
      type: 'list',
      title: "Top 10 Career Tackles (All-Time)",
      description: "List the top 10 NFL players by career tackles (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-tackles-all-times",
    },

    {
      type: 'list',
      title: "Top 10 Sacks (Last 10 Seasons)",
      description: "List the top 10 NFL players by total sacks over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-regular-season-sacks-over-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "Top 10 Interceptions (Last 10 Seasons)",
      description: "List the top 10 NFL players by total interceptions over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-interceptions-last-10-years",
    },

    {
      type: 'list',
      title: "Top 10 Forced Fumbles (Last 10 Seasons)",
      description: "List the top 10 NFL players by total forced fumbles over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-forced-fumbles-in-last-10-years",
    },

    {
      type: 'list',
      title: "Top 10 Tackles (Last 10 Seasons)",
      description: "List the top 10 NFL players by total tackles over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-tackles-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Passing TDs",
      description: "List the top 10 single-season passing touchdown totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-touchdown-passes-in-a-single-season",
    },

    {
      type: 'list',
      title: "Top 10 Career Passing TDs (All-Time)",
      description: "List the top 10 NFL players by career passing touchdowns (all-time).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-passing-touchdowns-nfl-history-by-player",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Rushing TDs",
      description: "List the top 10 single-season rushing touchdown totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-touchdowns-in-a-single-season",
    },

    {
      type: 'list',
      title: "Top 10 Career Rushing TDs (All-Time)",
      description: "List the top 10 NFL players by career rushing touchdowns (all-time).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-touchdowns-by-a-player-in-nfl-history",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Receiving TDs",
      description: "List the top 10 single-season receiving touchdown totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-touchdowns-single-season-nfl-history",
    },

    {
      type: 'list',
      title: "Top 10 Career Receiving TDs (All-Time)",
      description: "List the top 10 NFL players by career receiving touchdowns (all-time).",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-touchdowns-by-a-player-in-an-nfl-career",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Scrimmage Yards",
      description: "List the top 10 single-season scrimmage yard totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-yards-from-scrimmage-in-a-season-in-nfl-history",
    },

    {
      type: 'list',
      title: "Top 10 Career Scrimmage Yards (All-Time)",
      description: "List the top 10 NFL players by career scrimmage yards (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/nfl-yards-from-scrimmage-leaders",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Receptions",
      description: "List the top 10 single-season reception totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receptions-in-an-nfl-season-player",
    },

    {
      type: 'list',
      title: "Top 10 Career Receptions (All-Time)",
      description: "List the top 10 NFL players by career receptions (all-time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receptions-by-a-player-in-nfl-history",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season QB Rushing Yards",
      description: "List the top 10 single-season rushing yard totals by quarterbacks in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/nfl-most-rushing-yards-in-a-season-for-a-qb",
    },

    {
      type: 'list',
      title: "Top 10 Career QB Rushing Yards (All-Time)",
      description: "List the top 10 quarterbacks by career rushing yards in NFL history.",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-yards-by-a-quarterback-nfl-history",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Sacks",
      description: "List the top 10 single-season sack totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-sacks-by-player-in-a-single-season",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Interceptions (Player)",
      description: "List the top 10 single-season interception totals by a player in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-interceptions-in-a-nfl-season-by-a-player",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Team Sacks",
      description: "List the top 10 single-season team sack totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-sacks-by-a-team-in-one-season",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Team Points Scored",
      description: "List the top 10 single-season team points scored totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-points-scored-by-a-nfl-team-in-a-season",
    },

    {
      type: 'list',
      title: "Top 10 Single-Season Team Points Allowed (Best Defenses)",
      description: "List the top 10 lowest single-season team points allowed totals in NFL history.",
      category: "Single-Season",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/least-amount-of-points-allowed-by-an-nfl-team-in-a-single-season",
    },

    {
      type: 'list',
      title: "Top 10 Award Winners (Last 10 MVPs)",
      description: "Name the last 10 NFL MVP award winners.",
      category: "Awards",
      difficulty: 'Easy',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "",
    },

    {
      type: 'list',
      title: "Top 10 Award Winners (Last 10 OPOYs)",
      description: "Name the last 10 NFL Offensive Player of the Year award winners.",
      category: "Awards",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "",
    },

    {
      type: 'list',
      title: "Top 10 Award Winners (Last 10 DPOYs)",
      description: "Name the last 10 NFL Defensive Player of the Year award winners.",
      category: "Awards",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "",
    },

    {
      type: 'list',
      title: "Last 10 Super Bowl Winners",
      description: "Name the winners of the last 10 Super Bowls.",
      category: "Recent",
      difficulty: 'Easy',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/last-ten-superbowl-winners",
    },

    {
      type: 'list',
      title: "Last 10 Super Bowl MVPs",
      description: "Name the Super Bowl MVPs from the last 10 Super Bowls.",
      category: "Awards",
      difficulty: 'Medium',
      items: [
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
        { clue: "" },
      ],
      columns: 1,
      answerKeyUrl: "",
    },

    {
      type: 'list',
      title: "Top 10 Colleges by Active NFL Players",
      description: "List the top 10 colleges by number of active NFL players.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "",
    },

    {
      type: 'list',
      title: "Top 10 Colleges by Draft Picks (Last 10 Drafts)",
      description: "List the top 10 colleges by total NFL draft picks over the most recent 10 drafts.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "",
    },

    {
      type: 'list',
      title: "Top 10 Latest Draft Picks to Make a Pro Bowl",
      description: "List the top 10 latest-picked players (highest pick number) who made a Pro Bowl.",
      category: "Other",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "",
    },

    {
      type: 'teams',
      title: "Franchise Leaders: All-Time Passing Yards (32 Teams)",
      description: "Name each NFL team’s all-time leading passer by career passing yards.",
      category: "All-Time",
      difficulty: 'Hard',
      answerKeyUrl: "https://bit.ly/nfl-qb-leaders-by-team",
    },

    {
      type: 'teams',
      title: "Franchise Leaders: All-Time Rushing Yards (32 Teams)",
      description: "Name each NFL team’s all-time leading rusher by career rushing yards.",
      category: "All-Time",
      difficulty: 'Hard',
      answerKeyUrl: "",
    },

    {
      type: 'teams',
      title: "Franchise Leaders: All-Time Receiving Yards (32 Teams)",
      description: "Name each NFL team’s all-time leading receiver by career receiving yards.",
      category: "All-Time",
      difficulty: 'Hard',
      answerKeyUrl: "",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Passing TDs",
      description: "List the top 10 NFL players by total passing touchdowns over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Easy',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/who-has-the-most-passing-tds-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Rushing TDs",
      description: "List the top 10 NFL players by total rushing touchdowns over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-rushing-tds-by-a-player-in-the-last-10-seasons",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Receiving TDs",
      description: "List the top 10 NFL players by total receiving touchdowns over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-receiving-tds-in-last-10-years-per-season",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Interceptions",
      description: "List the top 10 NFL players by total interceptions over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-interceptions-last-10-years",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Passes Defended",
      description: "List the top 10 NFL players by total passes defended over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/who-has-the-most-pass-defended-last-10-years",
    },

    {
      type: 'list',
      title: "Last 10 Seasons: Most Tackles for Loss",
      description: "List the top 10 NFL players by total tackles for loss over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/nfl-tackles-for-loss-leaders-last-10-seasons-by-players",
    },

    {
      type: 'list',
      title: "Top 10 RB Receiving Yards (Last 10 Seasons)",
      description: "List the top 10 running backs in receiving yards over the most recent 10 NFL seasons.",
      category: "Recent",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask?q=most+receiving+yards+by+a+running+back+in+the+last+10+seasons",
    },

    {
      type: 'list',
      title: "Top 10 Non-QB Passing Yards (WR/TE/RB)",
      description: "List the top 10 players in passing yards among wide receivers, tight ends, and running backs (non-QBs).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask?q=most+passing+yards+by+wide+receiver%2C+tight-end%2C+and+runningback",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 200+ Rushing Yard Games",
      description: "List the top 10 players with the most games of 200+ rushing yards (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-200-yard-rushing-games",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 200+ Receiving Yard Games",
      description: "List the top 10 players with the most games of 200+ receiving yards (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-200-yard-receiving-games",
    },

    {
      type: 'list',
      title: "Top 10 QBs with Most 400+ Passing Yard Games",
      description: "List the top 10 quarterbacks with the most games of 400+ passing yards (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-400-yard-passing-games",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 3+ Rushing TD Games",
      description: "List the top 10 players with the most games with 3+ rushing touchdowns (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-career-games-3-rushing-touchdowns",
    },

    {
      type: 'list',
      title: "Top 10 Players with Most 3+ Receiving TD Games",
      description: "List the top 10 players with the most games with 3+ receiving touchdowns (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-career-games-with-3-receiving-tds",
    },

    {
      type: 'list',
      title: "Top 10 QBs with Most 5+ Passing TD Games",
      description: "List the top 10 quarterbacks with the most games with 5+ passing touchdowns (all time).",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.statmuse.com/nfl/ask/most-games-with-5-touchdown-passes",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Aaron Rodgers",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Aaron Rodgers",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/R/RodgAa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Tom Brady",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Tom Brady",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/B/BradTo00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Drew Brees",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Drew Brees",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/B/BreeDr00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Peyton Manning",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Peyton Manning",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/M/MannPe00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Brett Favre",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Brett Favre",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/F/FavrBr00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Philip Rivers",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Philip Rivers",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/R/RivePh00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Matthew Stafford",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Matthew Stafford",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/S/StafMa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Dan Marino",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Dan Marino",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/M/MariDa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Ben Roethlisberger",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Ben Roethlisberger",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/R/RoetBe00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Matt Ryan",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Matt Ryan",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/R/RyanMa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Eli Manning",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Eli Manning",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/M/MannEl00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Russell Wilson",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Russell Wilson",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/W/WilsRu00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Fran Tarkenton",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Fran Tarkenton",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/T/TarkFr00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by John Elway",
      description: "List the top 10 wide receivers with the most receiving touchdowns from John Elway",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/E/ElwaJo00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Kirk Cousins",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Kirk Cousins",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/C/CousKi00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Carson Palmer",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Carson Palmer",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/P/PalmCa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Warren Moon",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Warren Moon",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/M/MoonWa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Johnny Unitas",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Johnny Unitas",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/U/UnitJo00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Vinny Testaverde",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Vinny Testaverde",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/T/TestVi00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Joe Montana",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Joe Montana",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/M/MontJo01/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Joe Flacco",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Joe Flacco",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/F/FlacJo00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Patrick Mahomes",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Patrick Mahomes",
      category: "All-Time",
      difficulty: 'Medium',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/M/MahoPa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Dave Krieg",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Dave Krieg",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/K/KrieDa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Derek Carr",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Derek Carr",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/C/CarrDe02/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Jared Goff",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Jared Goff",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/G/GoffJa00/touchdowns/passing",
    },

    {
      type: 'list',
      title: "Top 10 player with the most receiving touchdowns thrown by Sonny Jurgensen",
      description: "List the top 10 wide receivers with the most receiving touchdowns from Sonny Jurgensen",
      category: "All-Time",
      difficulty: 'Hard',
      items: Array.from({length: 10}, (_, i) => ({
        clue: `#${i + 1}`,
      })),
      columns: 1,
      answerKeyUrl: "https://www.pro-football-reference.com/players/J/JurgSo00/touchdowns/passing",
    }
    ],
    getPageConfiguration(pageNum: number) {
      const pageIndex = pageNum - 1;
      if (pageIndex >= 0 && pageIndex < this.pages.length) {
        return this.pages[pageIndex];
      }
      return {
        type: 'text',
        content: `This is page ${pageNum} of our ${'nfl'.toUpperCase()} book. The content for this page is dynamically generated.`,
        answerKeyUrl: `https://example.com/page-${pageNum}-answers`
      };
    },
    getAnswerKeyUrl(pageNum: number): string {
      const pageConfiguration = this.getPageConfiguration(pageNum);
      return pageConfiguration.answerKeyUrl || `https://example.com/page-${pageNum}-answers`;
    },
    pageExists(pageNum: number): boolean {
      return pageNum >= 1 && pageNum <= this.pages.length;
    }
  },

  'nba': {
    pages: [
    {
      type: 'teams',
      title: "NBA — Franchise Leaders: All-Time Scoring (30 Teams)",
      description: "Name each NBA team’s all-time leading scorer",
      category: "30 items — clues are team names (all 30)",
      answerKeyUrl: "",
    }
    ],
    getPageConfiguration(pageNum: number) {
      const pageIndex = pageNum - 1;
      if (pageIndex >= 0 && pageIndex < this.pages.length) {
        return this.pages[pageIndex];
      }
      return {
        type: 'text',
        content: `This is page ${pageNum} of our ${'nba'.toUpperCase()} book. The content for this page is dynamically generated.`,
        answerKeyUrl: `https://example.com/page-${pageNum}-answers`
      };
    },
    getAnswerKeyUrl(pageNum: number): string {
      const pageConfiguration = this.getPageConfiguration(pageNum);
      return pageConfiguration.answerKeyUrl || `https://example.com/page-${pageNum}-answers`;
    },
    pageExists(pageNum: number): boolean {
      return pageNum >= 1 && pageNum <= this.pages.length;
    }
  }
};

// Aliasing for backward compatibility if ever needed directly (points to nfl by default)
export const pageConfig = booksConfig['nfl'];
